#!/bin/bash
# Preflight check - reminds Claude to check key resources before responding

echo "═══════════════════════════════════════════════════════════"
echo "⚠️  PREFLIGHT CHECK - Review before responding:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 CLAUDE.md CRITICAL RULES:"
echo "   • COMMIT every fix immediately (git add + git commit)"
echo "   • NEVER say 'fixed' without git diff"
echo "   • NEVER use destructive git commands without approval"
echo "   • Test buttons CLICK → action happens (not alert)"
echo "   • Test inputs TYPE → text visible"
echo ""
echo "🔍 CLAUDE MEMORY - Query for relevant past work:"
echo "   • Use mcp search before re-researching"
echo "   • Check if this bug/feature was worked on before"
echo ""
echo "🚨🚨🚨 MANDATORY QA — DO NOT SKIP 🚨🚨🚨"
echo "   After EVERY code change, BEFORE reporting to user:"
echo ""
echo "   node qa.cjs"
echo "   → Builds, launches browser, checks for crashes"
echo "   → Detects: error boundaries, ReferenceErrors, blank screens"
echo "   → Takes screenshot at /tmp/qa-screenshot.png"
echo "   → EXIT CODE 0 = PASS, non-zero = BROKEN"
echo ""
echo "   Then: Read /tmp/qa-screenshot.png (ACTUALLY VIEW IT)"
echo ""
echo "   If qa.cjs fails → FIX before reporting to user"
echo "   If dev server not running → npm run build + node screenshot.cjs"
echo ""
echo "═══════════════════════════════════════════════════════════"
